# Generated by Django 5.2.4 on 2025-07-24 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Órgão')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla do Órgão')),
                ('tipo', models.CharField(choices=[('INDIRETA', 'Administração Indireta'), ('DIRETA', 'Administração Direta'), ('CAMARA', 'Câmara Municipal'), ('TCM', 'Tribunal de Contas do Município')], default='DIRETA', max_length=20)),
            ],
            options={
                'verbose_name': 'Órgão',
                'verbose_name_plural': 'Órgãos',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='SubPrefeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Subprefeitura')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla da Subprefeitura')),
            ],
            options={
                'verbose_name': 'Subprefeitura',
                'verbose_name_plural': 'Subprefeituras',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Distrito')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla do Distrito')),
                ('subprefeitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='cadastros_basicos.subprefeitura')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ['sigla'],
            },
        ),
    ]
