version: '3.8'
 
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - traefik
 
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - traefik
    depends_on:
          - backend
 
networks:
  traefik:
    driver: bridge  