# Generated by Django 5.2.4 on 2025-07-24 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Eixo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Eixo')),
                ('resumo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resumo do Eixo')),
            ],
            options={
                'verbose_name': 'Eixo',
                'verbose_name_plural': 'Eixos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tema')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Tema')),
                ('eixos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='estrutura_pdm.eixo', verbose_name='Eixos relacionados')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['nome'],
            },
        ),
    ]
