# Generated by Django 5.2.4 on 2025-07-24 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='eixos',
        ),
        migrations.AddField(
            model_name='tema',
            name='eixo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='estrutura_pdm.eixo', verbose_name='Eixo relacionado'),
            preserve_default=False,
        ),
    ]
