# Generated by Django 5.2.4 on 2025-07-24 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0003_meta_acaoestrategica'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='eixo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='estrutura_pdm.eixo', verbose_name='Eixo relacionado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meta',
            name='tema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='estrutura_pdm.tema', verbose_name='Tema relacionado'),
            preserve_default=False,
        ),
    ]
