# Generated by Django 5.2.4 on 2025-07-24 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0001_initial'),
        ('estrutura_pdm', '0004_meta_eixo_meta_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaOrgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_orgao', to='estrutura_pdm.meta', verbose_name='Meta')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_orgao', to='cadastros_basicos.orgao', verbose_name='Órgão')),
            ],
            options={
                'verbose_name': 'Órgão Responsável pela Meta',
                'verbose_name_plural': 'Órgãos Responsáveis pelas Metas',
            },
        ),
    ]
