# Generated by Django 5.2.4 on 2025-07-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0007_meta_indicador_alter_meta_destaque_metasubprefeitura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='projecao',
            field=models.CharField(default='Projecao da meta', max_length=500, verbose_name='Projeção da Meta'),
            preserve_default=False,
        ),
    ]
