# Generated by Django 5.2.4 on 2025-07-25 20:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0008_meta_projecao'),
        ('static_files', '0002_alter_imagem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eixo',
            name='cor_principal',
            field=models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal no formato #RRGGBB (ex: #1A2B3C).', regex='^#([A-Fa-f0-9]{6})$')], verbose_name='Cor Principal do Eixo'),
        ),
        migrations.AddField(
            model_name='eixo',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eixo_estrategico', to='static_files.imagem', verbose_name='Logo do Eixo'),
        ),
    ]
