# Generated by Django 5.2.4 on 2025-07-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0009_eixo_cor_principal_eixo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eixo',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título do Eixo'),
        ),
    ]
