# Generated by Django 5.2.4 on 2025-07-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0010_eixo_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eixo',
            name='descricao',
            field=models.TextField(default='exemplo', verbose_name='Descrição do Eixo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eixo',
            name='resumo',
            field=models.CharField(default='exemplo', max_length=255, verbose_name='Resumo do Eixo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eixo',
            name='titulo',
            field=models.CharField(default='exemplo', max_length=200, verbose_name='Título do Eixo'),
            preserve_default=False,
        ),
    ]
