# Generated by Django 5.2.4 on 2025-07-28 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0011_alter_eixo_descricao_alter_eixo_resumo_and_more'),
        ('static_files', '0002_alter_imagem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eixo',
            old_name='logo',
            new_name='logo_colorido',
        ),
        migrations.AddField(
            model_name='eixo',
            name='logo_branco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eixo_estrategico_branco', to='static_files.imagem', verbose_name='Logo do Eixo (Branco)'),
        ),
    ]
