# Generated by Django 5.2.4 on 2025-08-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0013_alter_eixo_options_eixo_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['order'], 'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
        migrations.AddField(
            model_name='tema',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição'),
        ),
    ]
