# Generated by Django 5.2.4 on 2025-07-25 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secoes_pagina_inicial', '0002_noticia'),
        ('static_files', '0002_alter_imagem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpdm',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_pdm', to='static_files.imagem', verbose_name='Imagem Banner'),
        ),
    ]
