# Generated by Django 5.2.4 on 2025-07-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secoes_pagina_inicial', '0005_rename_publicado_noticia_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='colocar_no_topo',
            field=models.BooleanField(default=False, verbose_name='Colocar no topo - sobrescreve prioridade'),
        ),
    ]
