# Generated by Django 5.2.4 on 2025-08-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secoes_pagina_inicial', '0006_noticia_colocar_no_topo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpdm',
            name='paragrafo',
        ),
        migrations.AddField(
            model_name='aboutpdm',
            name='paragrafos',
            field=models.JSONField(default=list),
        ),
    ]
