# Generated by Django 5.2.4 on 2025-08-18 17:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0020_alter_pdm_options'),
        ('secoes_pagina_inicial', '0010_rename_paragrafocartapdm_paragrafocartaprefeito_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secoes_historico_criadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='secoes_historico_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seção Historico',
                'verbose_name_plural': 'Seções Historico',
            },
        ),
        migrations.CreateModel(
            name='CardHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem do Card')),
                ('conteudo', models.CharField(help_text='Conteúdo do card, que pode incluir informações sobre o PDM.', max_length=500, verbose_name='Conteúdo do Card')),
                ('cor_principal', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal no formato #RRGGBB (ex: #1A2B3C).', regex='^#([A-Fa-f0-9]{6})$')], verbose_name='Cor Principal do Eixo')),
                ('cor_botao', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal no formato #RRGGBB (ex: #1A2B3C).', regex='^#([A-Fa-f0-9]{6})$')], verbose_name='Cor do Botão')),
                ('pdm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_historico', to='estrutura_pdm.pdm', verbose_name='PDM Associado')),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='secoes_pagina_inicial.historico')),
            ],
            options={
                'verbose_name': 'Card do Histórico',
                'verbose_name_plural': 'Cards do Histórico',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ItemCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo do Item')),
                ('link', models.URLField(blank=True, help_text='Link opcional para mais informações sobre o item.', null=True, verbose_name='Link do Item')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem do Item')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='secoes_pagina_inicial.cardhistorico')),
            ],
            options={
                'verbose_name': 'Item do Card',
                'verbose_name_plural': 'Itens do Card',
                'ordering': ['ordem'],
            },
        ),
    ]
