# Generated by Django 5.2.4 on 2025-08-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secoes_pagina_inicial', '0011_historico_cardhistorico_itemcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemCard',
        ),
    ]
