# Generated by Django 5.2.4 on 2025-08-21 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secoes_pagina_inicial', '0012_delete_itemcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='descricao',
        ),
        migrations.AddField(
            model_name='historico',
            name='instrucao',
            field=models.TextField(default='Clique em cada documento para fazer seu download na íntegra', verbose_name='Instrução'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historico',
            name='parágrafo',
            field=models.TextField(default='O Programa de Metas de SP foi criado em 2008 para obrigar prefeitos a apresentar objetivos claros nos primeiros 90 dias de mandato. Desde então, cada gestão divulga metas para orientar ações e permitir o acompanhamento público, promovendo transparência e participação social.', help_text='Texto adicional que será exibido abaixo do título.', verbose_name='Parágrafo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardhistorico',
            name='conteudo',
            field=models.CharField(blank=True, help_text='Conteúdo do card, que pode incluir informações sobre o PDM.', max_length=500, null=True, verbose_name='Conteúdo do Card'),
        ),
        migrations.AlterField(
            model_name='cardhistorico',
            name='cor_principal',
            field=models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal no formato #RRGGBB (ex: #1A2B3C).', regex='^#([A-Fa-f0-9]{6})$')], verbose_name='Cor Principal do Card'),
        ),
    ]
