# Generated by Django 5.2.4 on 2025-08-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secoes_pagina_inicial', '0013_remove_historico_descricao_historico_instrucao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='parágrafo',
            new_name='paragrafo',
        ),
    ]
