# Generated by Django 5.2.4 on 2025-08-21 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secoes_pagina_inicial', '0014_rename_parágrafo_historico_paragrafo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecaoTransparencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Subtítulo')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secoes_transparencia_criadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='secoes_transparencia_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seção Transparência',
                'verbose_name_plural': 'Seções Transparência',
            },
        ),
        migrations.CreateModel(
            name='CardTransparencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Card')),
                ('conteudo', models.TextField(verbose_name='Conteúdo do Card')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem do Card')),
                ('botao_txt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Texto do Botão')),
                ('botao_url', models.URLField(verbose_name='URL do Botão')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('secao_transparencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='secoes_pagina_inicial.secaotransparencia')),
            ],
            options={
                'verbose_name': 'Card Transparência',
                'verbose_name_plural': 'Cards Transparência',
                'ordering': ['ordem'],
            },
        ),
    ]
