# Generated by Django 5.2.4 on 2025-08-25 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0025_alter_acaoorgao_acao_alter_acaoorgao_orgao_and_more'),
        ('secoes_pagina_inicial', '0015_secaotransparencia_cardtransparencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistorico',
            name='pdm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards_historico', to='estrutura_pdm.pdm', verbose_name='PDM Associado'),
        ),
        migrations.CreateModel(
            name='SecaoRegionalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=500, verbose_name='Subtítulo')),
                ('instrucao', models.TextField(verbose_name='Instrução')),
                ('link_arquivo', models.URLField(verbose_name='Link para Download do Arquivo')),
                ('link_dashboard', models.URLField(verbose_name='Link para Dashboard')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secoes_regionalizacao_criadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='secoes_regionalizacao_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seção Regionalização',
                'verbose_name_plural': 'Seções Regionalização',
            },
        ),
        migrations.CreateModel(
            name='ParagrafoSecaoRegionalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo do Parágrafo da Seção Regionalização')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem do Parágrafo')),
                ('secao_regionalizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragrafos', to='secoes_pagina_inicial.secaoregionalizacao')),
            ],
            options={
                'verbose_name': 'Parágrafo Regionalização',
                'verbose_name_plural': 'Parágrafos Regionalização',
                'ordering': ['ordem'],
            },
        ),
    ]
