# Generated by Django 5.2.4 on 2025-09-01 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secoes_pagina_inicial', '0016_alter_cardhistorico_pdm_secaoregionalizacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComoFeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto da chamada da seção Como é Feito')),
            ],
        ),
        migrations.CreateModel(
            name='CardComoFeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Número do Card')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Card')),
                ('conteudo', models.CharField(max_length=400, verbose_name='Conteúdo do Card')),
                ('detalhe', models.CharField(max_length=400, verbose_name='Detalhe do Card')),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='secoes_pagina_inicial.comofeito', verbose_name='Seção Como é Feito')),
            ],
            options={
                'verbose_name': 'Card Como É Feito',
                'verbose_name_plural': 'Cards Como É Feito',
            },
        ),
        migrations.CreateModel(
            name='SecaoSobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secao_sobre_criadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='secao_sobre_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seção Sobre',
                'verbose_name_plural': 'Seções Sobre',
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto da chamada da seção Participação Social')),
                ('conteudo_audiencias', models.CharField(max_length=800, verbose_name='Conteúdo da subseção Audiências Públicas')),
                ('link_video_audiencias', models.URLField(verbose_name='Link do vídeo das Audiências Públicas')),
                ('conteudo_devolutivas', models.CharField(max_length=800, verbose_name='Conteúdo da subseção Devolutivas')),
                ('secao_sobre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacao_social', to='secoes_pagina_inicial.secaosobre', verbose_name='Seção Sobre')),
            ],
        ),
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transparencia', models.CharField(max_length=800, verbose_name='Transparência')),
                ('visao_sistemica', models.CharField(max_length=800, verbose_name='Visão Sistêmica')),
                ('otimizacao', models.CharField(max_length=800, verbose_name='Otimização de Recursos')),
                ('execucao', models.CharField(max_length=800, verbose_name='Execução em Conjunto')),
                ('secao_sobre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='secoes_pagina_inicial.secaosobre', verbose_name='Seção Sobre')),
            ],
            options={
                'verbose_name': 'Objetivo PDM Sobre',
                'verbose_name_plural': 'Objetivos PDM Sobre',
            },
        ),
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto da chamada da seção Indicadores')),
                ('subtitulo', models.CharField(max_length=255, verbose_name='Subtítulo da seção Indicadores')),
                ('chamada_subsecao', models.CharField(max_length=500, verbose_name='Chamada da subseção Indicadores')),
                ('conteudo_subsecao', models.TextField(verbose_name='Conteúdo da subseção Indicadores')),
                ('secao_sobre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='secoes_pagina_inicial.secaosobre', verbose_name='Seção Sobre')),
            ],
        ),
        migrations.AddField(
            model_name='comofeito',
            name='secao_sobre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='como_feito', to='secoes_pagina_inicial.secaosobre', verbose_name='Seção Sobre'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supertitulo', models.CharField(max_length=255, verbose_name='Super Título')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=800, verbose_name='Subtítulo')),
                ('link_pdf', models.URLField(verbose_name='Link para o PDF do PDM')),
                ('what', models.CharField(max_length=800, verbose_name='O que é?')),
                ('why', models.CharField(max_length=800, verbose_name='Por que fazer o PDM?')),
                ('whom', models.CharField(max_length=800, verbose_name='Para quem é o PDM?')),
                ('secao_sobre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='secoes_pagina_inicial.secaosobre', verbose_name='Seção Sobre')),
            ],
            options={
                'verbose_name': 'Banner Sobre',
                'verbose_name_plural': 'Banners Sobre',
            },
        ),
    ]
