# Generated by Django 5.2.4 on 2025-09-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secoes_pagina_inicial', '0017_comofeito_cardcomofeito_secaosobre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardcomofeito',
            options={'ordering': ['numero'], 'verbose_name': 'Card Como É Feito', 'verbose_name_plural': 'Cards Como É Feito'},
        ),
    ]
