# Generated by Django 5.2.4 on 2025-09-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secoes_pagina_inicial', '0018_alter_cardcomofeito_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtransparencia',
            name='botao_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do Botão'),
        ),
    ]
