# Generated by Django 5.2.4 on 2026-02-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secoes_pagina_inicial', '0019_alter_cardtransparencia_botao_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link_pdf2',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Link para o segundo PDF'),
        ),
    ]
