# Generated by Django 5.2.4 on 2026-02-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secoes_pagina_inicial', '0020_banner_link_pdf2'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpdm',
            name='link_pdf_about',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Link para o PDF'),
        ),
    ]
