# Generated by Django 5.2.4 on 2025-07-23 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubPrefeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Subprefeitura')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla da Subprefeitura')),
            ],
            options={
                'verbose_name': 'Subprefeitura',
                'verbose_name_plural': 'Subprefeituras',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Distrito')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla do Distrito')),
                ('subprefeitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='pdm_admin.subprefeitura')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ['sigla'],
            },
        ),
    ]
