# Generated by Django 5.2.4 on 2025-07-23 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdm_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEnte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria do Ente')),
                ('descricao', models.TextField(verbose_name='Descrição da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Ente',
                'verbose_name_plural': 'Categorias de Entes',
                'ordering': ['categoria'],
            },
        ),
        migrations.CreateModel(
            name='Ente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000, verbose_name='Nome do Ente')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla do Ente')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entes', to='pdm_admin.categoriaente', verbose_name='Categoria do Ente')),
            ],
            options={
                'verbose_name': 'Ente',
                'verbose_name_plural': 'Entes',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Órgão')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla do Órgão')),
                ('ente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgaos', to='pdm_admin.ente', verbose_name='Ente ao qual pertence o Órgão')),
            ],
            options={
                'verbose_name': 'Órgão',
                'verbose_name_plural': 'Órgãos',
                'ordering': ['sigla'],
            },
        ),
    ]
