# Generated by Django 5.2.4 on 2025-07-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdm_admin', '0002_categoriaente_ente_orgao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ente',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='orgao',
            name='ente',
        ),
        migrations.AddField(
            model_name='orgao',
            name='tipo',
            field=models.CharField(choices=[('INDIRETA', 'Administração Indireta'), ('DIRETA', 'Administração Direta'), ('CAMARA', 'Câmara Municipal'), ('TCM', 'Tribunal de Contas do Município')], default='DIRETA', max_length=20),
        ),
        migrations.DeleteModel(
            name='CategoriaEnte',
        ),
        migrations.DeleteModel(
            name='Ente',
        ),
    ]
