# Generated by Django 5.2.4 on 2025-08-29 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros_basicos', '0009_zona_subprefeitura_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canais',
            },
        ),
        migrations.CreateModel(
            name='OrigensContribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.CreateModel(
            name='Contribuicao',
            fields=[
                ('id_contribuicao', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('id_participe_mais', models.CharField(blank=True, max_length=36, null=True)),
                ('titulo', models.CharField(blank=True, max_length=600, null=True)),
                ('resumo', models.CharField(blank=True, max_length=1000, null=True)),
                ('conteudo', models.TextField()),
                ('qtd_apoios', models.IntegerField(blank=True, null=True)),
                ('qtd_comentarios', models.IntegerField(blank=True, null=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contribuicoes', to='devolutivas.canal')),
            ],
            options={
                'verbose_name': 'Contribuição',
                'verbose_name_plural': 'Contribuições',
            },
        ),
        migrations.CreateModel(
            name='ContribuicaoSubPrefeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribuicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contribuicoes_subprefeituras', to='devolutivas.contribuicao', verbose_name='Contribuição')),
                ('subprefeitura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contribuicao_subprefeitura', to='cadastros_basicos.subprefeitura', verbose_name='Subprefeitura')),
            ],
            options={
                'verbose_name': 'Subprefeitura relacionada à Contribuição',
                'verbose_name_plural': 'Subprefeituras relacionadas às Contribuições',
            },
        ),
        migrations.AddField(
            model_name='contribuicao',
            name='subprefeituras',
            field=models.ManyToManyField(blank=True, related_name='contribuicoes', through='devolutivas.ContribuicaoSubPrefeitura', to='cadastros_basicos.subprefeitura', verbose_name='Subprefeituras relacionadas à Contribuição'),
        ),
        migrations.CreateModel(
            name='Devolutiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField()),
                ('contribuicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolutivas', to='devolutivas.contribuicao', verbose_name='Contribuição')),
            ],
            options={
                'verbose_name': 'Devolutiva',
                'verbose_name_plural': 'Devolutivas',
            },
        ),
        migrations.CreateModel(
            name='DevolutivaOrgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devolutiva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolutivas_orgaos', to='devolutivas.devolutiva', verbose_name='Devolutiva')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolutiva_orgao', to='cadastros_basicos.orgao', verbose_name='Órgão')),
            ],
            options={
                'verbose_name': 'Órgão Responsável pela Devolutiva',
                'verbose_name_plural': 'Órgãos Responsáveis pelas Devolutivas',
            },
        ),
        migrations.AddField(
            model_name='devolutiva',
            name='orgaos_responsaveis',
            field=models.ManyToManyField(blank=True, related_name='devolutivas', through='devolutivas.DevolutivaOrgao', to='cadastros_basicos.orgao', verbose_name='Órgãos responsáveis pela Devolutiva'),
        ),
        migrations.AddField(
            model_name='contribuicao',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contribuicoes', to='devolutivas.origenscontribuicao'),
        ),
        migrations.AddField(
            model_name='devolutiva',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolutivas', to='devolutivas.tema', verbose_name='Tema'),
        ),
        migrations.AlterUniqueTogether(
            name='contribuicao',
            unique_together={('id_contribuicao', 'origem')},
        ),
    ]
