# Generated by Django 5.2.4 on 2025-08-29 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0009_zona_subprefeitura_zona'),
        ('devolutivas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolutiva',
            name='orgaos_responsaveis',
        ),
        migrations.AddField(
            model_name='devolutiva',
            name='orgao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='devolutivas', to='cadastros_basicos.orgao', verbose_name='Órgão Responsável pela Devolutiva'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DevolutivaOrgao',
        ),
    ]
