# Generated by Django 5.2.4 on 2025-08-29 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0009_zona_subprefeitura_zona'),
        ('devolutivas', '0002_remove_devolutiva_orgaos_responsaveis_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devolutiva',
            unique_together={('contribuicao', 'tema', 'orgao', 'resposta')},
        ),
    ]
