# Generated by Django 5.2.4 on 2025-08-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolutivas', '0003_alter_devolutiva_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuicao',
            name='origem',
            field=models.CharField(choices=[('fala', 'Fala em Audiência Pública'), ('revisao', 'Sugestão de Revisão/Alteração no Participe+'), ('proposta', 'Proposta no Participe+')], max_length=20),
        ),
        migrations.DeleteModel(
            name='OrigensContribuicao',
        ),
    ]
