# Generated by Django 5.2.4 on 2025-08-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolutivas', '0004_alter_contribuicao_origem_delete_origenscontribuicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuicao',
            name='municipe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
