# Generated by Django 5.2.4 on 2025-08-29 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolutivas', '0005_contribuicao_municipe'),
        ('static_files', '0002_alter_imagem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSecaoApresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Modal')),
                ('subtitulo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Subtítulo do Modal')),
                ('imagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secao_devolutivas_modal', to='static_files.imagem', verbose_name='Imagem Background da Seção Devolutivas')),
            ],
        ),
        migrations.CreateModel(
            name='SecaoParticipacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Seção')),
                ('subtitulo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Subtítulo da Seção')),
                ('texto', models.TextField(verbose_name='Texto da Seção')),
                ('subtitulo_box', models.CharField(blank=True, max_length=500, null=True, verbose_name='Subtítulo do Box Devolutivas')),
                ('texto_box', models.TextField(verbose_name='Texto do Box Devolutivas')),
                ('imagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secao_devolutivas', to='static_files.imagem', verbose_name='Imagem Background da Seção Devolutivas')),
                ('modal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devolutivas.subsecaoapresentacao', verbose_name='Modal de Apresentação')),
            ],
        ),
        migrations.CreateModel(
            name='ParagrafoApresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo do Parágrafo')),
                ('apresentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragrafos', to='devolutivas.subsecaoapresentacao')),
            ],
        ),
    ]
