# Generated by Django 5.2.4 on 2025-08-29 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolutivas', '0006_subsecaoapresentacao_secaoparticipacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsecaoapresentacao',
            name='secao',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modal_secao', to='devolutivas.secaoparticipacao'),
            preserve_default=False,
        ),
    ]
