# Generated by Django 5.2.4 on 2025-08-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolutivas', '0007_subsecaoapresentacao_secao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secaoparticipacao',
            name='texto',
        ),
        migrations.AddField(
            model_name='subsecaoapresentacao',
            name='texto',
            field=models.TextField(default='Aaaa', verbose_name='Texto da Seção'),
            preserve_default=False,
        ),
    ]
