# Generated by Django 5.2.4 on 2025-08-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devolutivas', '0008_remove_secaoparticipacao_texto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secaoparticipacao',
            name='modal',
        ),
    ]
