# Generated by Django 5.2.4 on 2025-08-29 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolutivas', '0009_remove_secaoparticipacao_modal'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkYoutubeAudiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL do Vídeo no YouTube')),
                ('tipo_link', models.CharField(choices=[('listing', 'Links que ficam nos listings'), ('destaque', 'Link que fica no destaque'), ('botao', 'Link que vai para o botao')], max_length=20)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_youtube', to='devolutivas.secaoparticipacao')),
            ],
        ),
    ]
