# Generated by Django 5.2.4 on 2026-03-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolutivas', '0010_linkyoutubeaudiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuicao',
            name='origem',
            field=models.CharField(choices=[('fala', 'Fala em\n Audiência Pública'), ('revisao', 'Sugestão de Revisão/\nAlteração no Participe+'), ('proposta', 'Proposta no\n Participe+')], max_length=20),
        ),
    ]
