# Generated by Django 5.2.4 on 2025-07-25 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo', models.ImageField(upload_to='imagens/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('largura', models.PositiveIntegerField(blank=True, null=True)),
                ('altura', models.PositiveIntegerField(blank=True, null=True)),
                ('formato', models.CharField(blank=True, max_length=20)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
