# Generated by Django 5.2.4 on 2025-07-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagem',
            options={'verbose_name': 'Imagem', 'verbose_name_plural': 'Imagens'},
        ),
    ]
