# Generated by Django 5.2.4 on 2025-07-25 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=500, verbose_name='Subtítulo')),
                ('paragrafo', models.TextField(verbose_name='Parágrafo')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='secoes_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seção Sobre o PDM',
                'verbose_name_plural': 'Seções Sobre o PDM',
            },
        ),
    ]
