# Generated by Django 5.2.4 on 2025-07-25 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secoes_pagina_inicial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('link', models.URLField(max_length=500, verbose_name='Link')),
                ('data', models.DateField(verbose_name='Data')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noticias_criadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='noticias_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
            },
        ),
    ]
