# Generated by Django 5.2.4 on 2025-07-25 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secoes_pagina_inicial', '0003_aboutpdm_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='prioridade',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prioridade'),
        ),
    ]
