# Generated by Django 5.2.4 on 2025-07-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secoes_pagina_inicial', '0004_noticia_prioridade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='publicado',
            new_name='published',
        ),
    ]
