# Generated by Django 5.2.4 on 2025-08-06 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secoes_pagina_inicial', '0007_remove_aboutpdm_paragrafo_aboutpdm_paragrafos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpdm',
            name='paragrafos',
        ),
        migrations.CreateModel(
            name='ParagrafoAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo do Parágrafo')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem do Parágrafo')),
                ('sobre_pdm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragrafos', to='secoes_pagina_inicial.aboutpdm')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
