# Generated by Django 5.2.4 on 2025-08-06 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0004_prefeito'),
        ('secoes_pagina_inicial', '0008_remove_aboutpdm_paragrafos_paragrafoabout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paragrafoabout',
            options={'ordering': ['ordem'], 'verbose_name': 'Parágrafo', 'verbose_name_plural': 'Parágrafos'},
        ),
        migrations.AlterField(
            model_name='aboutpdm',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secoes_about_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aboutpdm',
            name='modificado_por',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='secoes_about_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CartaPrefeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Subtítulo')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartas_prefeito_criadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='cartas_prefeito_modificadas', to=settings.AUTH_USER_MODEL)),
                ('prefeito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartas', to='cadastros_basicos.prefeito', verbose_name='Prefeito')),
            ],
            options={
                'verbose_name': 'Carta do Prefeito',
                'verbose_name_plural': 'Cartas do Prefeito',
            },
        ),
        migrations.AddField(
            model_name='aboutpdm',
            name='carta_do_prefeito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='about_pdm', to='secoes_pagina_inicial.cartaprefeito', verbose_name='Carta do Prefeito'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ParagrafoCartaPDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo do Parágrafo da Carta do Prefeito')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem do Parágrafo')),
                ('carta_do_prefeito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragrafos', to='secoes_pagina_inicial.cartaprefeito')),
            ],
            options={
                'verbose_name': 'Parágrafo',
                'verbose_name_plural': 'Parágrafos',
                'ordering': ['ordem'],
            },
        ),
    ]
