# Generated by Django 5.2.4 on 2025-08-06 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secoes_pagina_inicial', '0009_alter_paragrafoabout_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParagrafoCartaPDM',
            new_name='ParagrafoCartaPrefeito',
        ),
        migrations.AddField(
            model_name='cartaprefeito',
            name='data_assinatura',
            field=models.DateField(default=datetime.date(2025, 8, 6), verbose_name='Data de Assinatura'),
            preserve_default=False,
        ),
    ]
