# Generated by Django 5.2.4 on 2025-07-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0001_initial'),
        ('estrutura_pdm', '0005_metaorgao'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='orgaos_responsaveis',
            field=models.ManyToManyField(blank=True, related_name='metas', through='estrutura_pdm.MetaOrgao', to='cadastros_basicos.orgao', verbose_name='Órgãos responsáveis'),
        ),
    ]
