# Generated by Django 5.2.4 on 2025-07-25 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0001_initial'),
        ('estrutura_pdm', '0006_meta_orgaos_responsaveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='indicador',
            field=models.CharField(default='Indicador padrao', max_length=500, verbose_name='Indicador da Meta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meta',
            name='destaque',
            field=models.CharField(max_length=500, unique=True, verbose_name='Destaque da Meta'),
        ),
        migrations.CreateModel(
            name='MetaSubprefeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_subprefeitura', to='estrutura_pdm.meta', verbose_name='Meta')),
                ('subprefeitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_subprefeitura', to='cadastros_basicos.subprefeitura', verbose_name='Subprefeitura')),
            ],
            options={
                'verbose_name': 'Subprefeitura Responsável pela Meta',
                'verbose_name_plural': 'Subprefeituras Responsáveis pelas Metas',
            },
        ),
        migrations.AddField(
            model_name='meta',
            name='subprefeituras_entregas',
            field=models.ManyToManyField(blank=True, related_name='metas', through='estrutura_pdm.MetaSubprefeitura', to='cadastros_basicos.subprefeitura', verbose_name='Subprefeituras com entregas'),
        ),
    ]
