# Generated by Django 5.2.4 on 2025-08-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0012_rename_logo_eixo_logo_colorido_eixo_logo_branco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eixo',
            options={'ordering': ['ordem'], 'verbose_name': 'Eixo', 'verbose_name_plural': 'Eixos'},
        ),
        migrations.AddField(
            model_name='eixo',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição dos eixos. Eixos com ordem menor serão exibidos primeiro.', verbose_name='Ordem de Exibição'),
        ),
    ]
