# Generated by Django 5.2.4 on 2025-08-12 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0005_alter_orgao_nome_alter_orgao_sigla'),
        ('estrutura_pdm', '0014_alter_tema_options_tema_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acaoestrategica',
            options={'ordering': ['meta__numero', 'posicao'], 'verbose_name': 'Ação Estratégica', 'verbose_name_plural': 'Ações Estratégicas'},
        ),
        migrations.AddField(
            model_name='acaoestrategica',
            name='numero',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Número da Ação Estratégica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acaoestrategica',
            name='orgao_responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='acoes_estrategicas', to='cadastros_basicos.orgao', verbose_name='Órgão Responsável'),
            preserve_default=False,
        ),
    ]
