# Generated by Django 5.2.4 on 2025-08-13 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0005_alter_orgao_nome_alter_orgao_sigla'),
        ('estrutura_pdm', '0015_alter_acaoestrategica_options_acaoestrategica_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acaoestrategica',
            name='orgao_responsavel',
        ),
        migrations.CreateModel(
            name='AcaoOrgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_estrategicas', to='estrutura_pdm.acaoestrategica', verbose_name='Ações Estratégicas')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acao_orgao', to='cadastros_basicos.orgao', verbose_name='Órgão')),
            ],
            options={
                'verbose_name': 'Órgão Responsável pela Ação Estratégica',
                'verbose_name_plural': 'Órgãos Responsáveis pelas Ações Estratégicas',
            },
        ),
        migrations.AddField(
            model_name='acaoestrategica',
            name='orgaos_responsaveis',
            field=models.ManyToManyField(blank=True, related_name='acoes_estrategicas', through='estrutura_pdm.AcaoOrgao', to='cadastros_basicos.orgao', verbose_name='Órgãos responsáveis pela Ação Estratégica'),
        ),
    ]
