# Generated by Django 5.2.4 on 2025-08-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0016_remove_acaoestrategica_orgao_responsavel_acaoorgao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaoestrategica',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição da Ação Estratégica'),
        ),
    ]
