# Generated by Django 5.2.4 on 2025-08-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0017_alter_acaoestrategica_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaoestrategica',
            name='descricao',
            field=models.CharField(max_length=5000, verbose_name='Descrição da Ação Estratégica'),
        ),
    ]
