# Generated by Django 5.2.4 on 2025-08-18 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0008_alter_planosetorial_options'),
        ('estrutura_pdm', '0018_alter_acaoestrategica_descricao'),
        ('static_files', '0002_alter_imagem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do PDM')),
                ('descricao', models.TextField(verbose_name='Descrição do PDM')),
                ('ano_inicio', models.IntegerField(unique=True, verbose_name='Ano de Início')),
                ('ano_fim', models.IntegerField(unique=True, verbose_name='Ano de Fim')),
                ('capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdm_capa', to='static_files.imagem', verbose_name='Capa do PDM')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdm_logo', to='static_files.imagem', verbose_name='Logo do PDM')),
                ('prefeito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdm_prefeito', to='cadastros_basicos.prefeito', verbose_name='Prefeito que elaborou o PDM')),
            ],
            options={
                'verbose_name': 'PDM',
                'verbose_name_plural': 'PDMs',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('ano_inicio', 'ano_fim'), name='unique_periodo_pdm')],
            },
        ),
    ]
