# Generated by Django 5.2.4 on 2025-08-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0019_pdm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdm',
            options={'ordering': ['ano_fim'], 'verbose_name': 'PDM', 'verbose_name_plural': 'PDMs'},
        ),
    ]
