# Generated by Django 5.2.4 on 2025-08-21 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0020_alter_pdm_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome do Documento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Documento')),
                ('tipo', models.CharField(choices=[('pdm', 'Programa de Metas'), ('relatorio', 'Relatório  de Execução'), ('outro', 'Outro')], max_length=50, verbose_name='Tipo de Documento')),
                ('url', models.URLField(verbose_name='Link para Arquivo do Documento')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem do Documento')),
                ('pdm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='estrutura_pdm.pdm', verbose_name='PDM')),
            ],
            options={
                'verbose_name': 'Documento PDM',
                'verbose_name_plural': 'Documentos PDM',
                'ordering': ['tipo', 'ordem'],
            },
        ),
    ]
