# Generated by Django 5.2.4 on 2025-08-21 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0021_documentopdm'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoPDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome do Tipo de Documento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Tipo de Documento PDM',
                'verbose_name_plural': 'Tipos de Documentos PDM',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='documentopdm',
            options={'ordering': ['tipo__nome', 'ordem'], 'verbose_name': 'Documento PDM', 'verbose_name_plural': 'Documentos PDM'},
        ),
        migrations.AlterField(
            model_name='documentopdm',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estrutura_pdm.tipodocumentopdm', verbose_name='Tipo de Documento'),
        ),
    ]
