# Generated by Django 5.2.4 on 2025-08-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0022_tipodocumentopdm_alter_documentopdm_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eixo',
            name='orcamento',
            field=models.IntegerField(default=0, help_text='Orçamento total alocado para este eixo.', verbose_name='Orçamento do Eixo'),
        ),
    ]
