# Generated by Django 5.2.4 on 2025-08-21 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0023_eixo_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='eixo',
            name='pdm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='eixos', to='estrutura_pdm.pdm', verbose_name='PDM Associado'),
            preserve_default=False,
        ),
    ]
