# Generated by Django 5.2.4 on 2025-08-21 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0008_alter_planosetorial_options'),
        ('estrutura_pdm', '0024_eixo_pdm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaoorgao',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_estrategicas', to='estrutura_pdm.acaoestrategica', verbose_name='Ações Estratégicas'),
        ),
        migrations.AlterField(
            model_name='acaoorgao',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acao_orgao', to='cadastros_basicos.orgao', verbose_name='Órgão'),
        ),
        migrations.AlterField(
            model_name='metaorgao',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meta_orgao', to='estrutura_pdm.meta', verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='metaorgao',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meta_orgao', to='cadastros_basicos.orgao', verbose_name='Órgão'),
        ),
    ]
