# Generated by Django 5.2.4 on 2025-08-27 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0009_zona_subprefeitura_zona'),
        ('estrutura_pdm', '0025_alter_acaoorgao_acao_alter_acaoorgao_orgao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metasubprefeitura',
            options={'verbose_name': 'Subprefeitura que a Meta possui entregas', 'verbose_name_plural': 'Subprefeituras que a Meta possui entregas'},
        ),
        migrations.CreateModel(
            name='MetaZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_zona', to='estrutura_pdm.meta', verbose_name='Meta')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_zona', to='cadastros_basicos.zona', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Zona que a Meta possui entregas',
                'verbose_name_plural': 'Zonas que a Meta possui entregas',
            },
        ),
        migrations.AddField(
            model_name='meta',
            name='zonas_entregas',
            field=models.ManyToManyField(blank=True, related_name='metas', through='estrutura_pdm.MetaZona', to='cadastros_basicos.zona', verbose_name='Zonas com entregas'),
        ),
    ]
