# Generated by Django 5.2.4 on 2025-08-27 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0009_zona_subprefeitura_zona'),
        ('estrutura_pdm', '0026_alter_metasubprefeitura_options_metazona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_ods', to='estrutura_pdm.meta', verbose_name='Meta')),
                ('ods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_ods', to='cadastros_basicos.ods', verbose_name='ODS')),
            ],
            options={
                'verbose_name': 'ODS relacionado à Meta',
                'verbose_name_plural': 'ODS relacionado à Meta',
            },
        ),
        migrations.AddField(
            model_name='meta',
            name='ods_relacionados',
            field=models.ManyToManyField(blank=True, related_name='metas', through='estrutura_pdm.MetaODS', to='cadastros_basicos.ods', verbose_name='ODS relacionados'),
        ),
        migrations.CreateModel(
            name='MetaPlanoSetorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_plano_setorial', to='estrutura_pdm.meta', verbose_name='Meta')),
                ('plano_setorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_plano_setorial', to='cadastros_basicos.planosetorial', verbose_name='Plano Setorial')),
            ],
            options={
                'verbose_name': 'Plano Setorial relacionado à Meta',
                'verbose_name_plural': 'Planos relacionado à Meta',
            },
        ),
        migrations.AddField(
            model_name='meta',
            name='planos_setoriais_relacionados',
            field=models.ManyToManyField(blank=True, related_name='metas', through='estrutura_pdm.MetaPlanoSetorial', to='cadastros_basicos.planosetorial', verbose_name='Planos Setoriais relacionados'),
        ),
    ]
