# Generated by Django 5.2.4 on 2025-08-28 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0027_metaods_meta_ods_relacionados_metaplanosetorial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eixo',
            name='cor_secundaria',
            field=models.CharField(blank=True, default='#000000', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal no formato #RRGGBB (ex: #1A2B3C).', regex='^#([A-Fa-f0-9]{6})$')], verbose_name='Cor Secundária do Eixo'),
        ),
    ]
