# Generated by Django 5.2.4 on 2025-10-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0028_eixo_cor_secundaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='status_regionalizacao',
            field=models.CharField(choices=[('não regionalizável', 'Nao Regionalizavel'), ('regionalizável', 'Regionalizavel'), ('regionalizada', 'Regionalizada')], default='não regionalizável', max_length=50, verbose_name='Status de Regionalização'),
        ),
    ]
