# Generated by Django 5.2.4 on 2025-10-13 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0029_meta_status_regionalizacao'),
        ('static_files', '0002_alter_imagem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapaMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador_legenda', models.TextField(verbose_name='Indicador da Legenda do Mapa')),
                ('nota_rodape', models.TextField(verbose_name='Nota de rodapé do mapa')),
                ('frase_regionalizacao', models.TextField(verbose_name='Frase para quando a meta é regionalizável')),
                ('map_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapa_meta', to='static_files.imagem', verbose_name='Mapa da Meta')),
                ('meta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapa', to='estrutura_pdm.meta', verbose_name='Meta')),
            ],
        ),
    ]
