# Generated by Django 5.2.4 on 2025-10-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0030_mapameta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapameta',
            name='frase_regionalizacao',
            field=models.TextField(blank=True, null=True, verbose_name='Frase para quando a meta é regionalizável'),
        ),
    ]
