# Generated by Django 5.2.4 on 2025-10-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0031_alter_mapameta_frase_regionalizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapameta',
            name='indicador_legenda',
            field=models.TextField(blank=True, null=True, verbose_name='Indicador da Legenda do Mapa'),
        ),
        migrations.AlterField(
            model_name='mapameta',
            name='nota_rodape',
            field=models.TextField(blank=True, null=True, verbose_name='Nota de rodapé do mapa'),
        ),
    ]
