# Generated by Django 5.2.4 on 2026-02-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0032_alter_mapameta_indicador_legenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaoestrategica',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
