# Generated by Django 5.2.4 on 2026-02-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0033_acaoestrategica_concluida'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='status_monitoramento',
            field=models.CharField(choices=[('planejamento', 'Em planejamento'), ('progresso', 'Em progresso'), ('atingida', 'Meta atingida')], default='planejamento', max_length=50, verbose_name='Monitoramento'),
        ),
    ]
