# Generated by Django 5.2.4 on 2026-02-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0034_meta_status_monitoramento'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='evolucao',
            field=models.TextField(blank=True, null=True, verbose_name='Evolução da Meta'),
        ),
    ]
