# Generated by Django 5.2.4 on 2026-02-25 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0035_meta_evolucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadosApurados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdd', models.IntegerField(verbose_name='Quantidade de Resultados Apurados')),
                ('mes', models.CharField(choices=[('', 'Selecione uma opção'), ('JAN', 'JAN'), ('FEV', 'FEV'), ('MAR', 'MAR'), ('ABR', 'ABR'), ('MAIO', 'MAIO'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AGO', 'AGO'), ('SET', 'SET'), ('OUT', 'OUT'), ('NOV', 'NOV'), ('DEZ', 'DEZ')], verbose_name='Mês (data)')),
                ('ano', models.IntegerField(verbose_name='Ano (data)')),
                ('data', models.DateField(editable=False)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_apurados', to='estrutura_pdm.meta', verbose_name='Meta relacionada')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
