# Generated by Django 5.2.4 on 2026-03-12 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0036_resultadosapurados'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConhecaMetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('recursos_empenhados', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Recursos Empenhados até o Momento')),
                ('metas_atingidas', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Metas Atingidas')),
                ('metas_mais_50', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Metas com mais de 50% de Execução')),
                ('metas_andamento_atingida', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Metas em Andamento ou/e Atingidas (%)')),
                ('execucao_total', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Execução Total do PdM (%)')),
            ],
        ),
    ]
