# Generated by Django 5.2.4 on 2026-03-12 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0037_conhecametas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conhecametas',
            name='metas_andamento_atingida',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Metas em Andamento ou/e Atingidas (%)'),
        ),
    ]
