# Generated by Django 5.2.4 on 2026-03-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0038_alter_conhecametas_metas_andamento_atingida'),
    ]

    operations = [
        migrations.AddField(
            model_name='conhecametas',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
    ]
