# Generated by Django 5.2.4 on 2026-03-12 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0039_conhecametas_publicado'),
        ('static_files', '0002_alter_imagem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapaAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador_legenda', models.TextField(blank=True, null=True, verbose_name='Indicador de Legenda do Mapa')),
                ('nota_rodape', models.TextField(blank=True, null=True, verbose_name='Nota de rodapé do mapa')),
                ('map_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_abstract', to='static_files.imagem', verbose_name='Mapa da Meta')),
                ('meta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapa_abstract', to='estrutura_pdm.meta', verbose_name='Meta')),
            ],
        ),
        migrations.AlterModelOptions(
            name='conhecametas',
            options={'verbose_name': 'Conheça as Metas', 'verbose_name_plural': 'Conheça as Metas'},
        ),
        migrations.RemoveField(
            model_name='mapameta',
            name='indicador_legenda',
        ),
        migrations.RemoveField(
            model_name='mapameta',
            name='map_image',
        ),
        migrations.RemoveField(
            model_name='mapameta',
            name='nota_rodape',
        ),
        migrations.CreateModel(
            name='MapaExecutado',
            fields=[
                ('mapaabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estrutura_pdm.mapaabstract')),
                ('mapa_meta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapa_executado', to='estrutura_pdm.mapameta', verbose_name='MapaMeta')),
            ],
            bases=('estrutura_pdm.mapaabstract',),
        ),
        migrations.CreateModel(
            name='MapaPlanejado',
            fields=[
                ('mapaabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estrutura_pdm.mapaabstract')),
                ('mapa_meta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapa_planejado', to='estrutura_pdm.mapameta', verbose_name='MapaMeta')),
            ],
            bases=('estrutura_pdm.mapaabstract',),
        ),
    ]
