# Generated by Django 5.2.4 on 2026-03-13 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0040_mapaabstract_alter_conhecametas_options_and_more'),
        ('static_files', '0002_alter_imagem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapaabstract',
            name='meta',
        ),
        migrations.AddField(
            model_name='mapaexecutado',
            name='meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapa_executado', to='estrutura_pdm.meta', verbose_name='Meta'),
        ),
        migrations.AddField(
            model_name='mapaplanejado',
            name='meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapa_planejado', to='estrutura_pdm.meta', verbose_name='Meta'),
        ),
        migrations.CreateModel(
            name='MapaMetaAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador_legenda', models.TextField(blank=True, null=True, verbose_name='Indicador da Legenda do Mapa')),
                ('nota_rodape', models.TextField(blank=True, null=True, verbose_name='Nota de rodapé do mapa')),
                ('frase_regionalizacao', models.TextField(blank=True, null=True, verbose_name='Frase para quando a meta é regionalizável')),
                ('map_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapa_meta', to='static_files.imagem', verbose_name='Mapa da Meta')),
                ('meta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapa_meta_abstract', to='estrutura_pdm.meta', verbose_name='Meta')),
            ],
        ),
    ]
