# Generated by Django 5.2.4 on 2026-03-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0041_remove_mapaabstract_meta_mapaexecutado_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaoestrategica',
            name='descricao_evolucao',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Descrição da Evolução'),
        ),
        migrations.AddField(
            model_name='acaoestrategica',
            name='evolucao_negrito',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Texto de Evolução (Negrito)'),
        ),
    ]
