# Generated by Django 5.2.4 on 2026-03-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0042_acaoestrategica_descricao_evolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadosapurados',
            name='qtdd',
        ),
        migrations.AddField(
            model_name='resultadosapurados',
            name='resultado_value',
            field=models.CharField(default='-', max_length=500, verbose_name='Valor de Resultados Apurados'),
        ),
    ]
