# Generated by Django 5.2.4 on 2026-03-27 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0043_remove_resultadosapurados_qtdd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conhecametas',
            name='execucao_total',
        ),
        migrations.RemoveField(
            model_name='conhecametas',
            name='metas_andamento_atingida',
        ),
        migrations.RemoveField(
            model_name='conhecametas',
            name='metas_atingidas',
        ),
        migrations.RemoveField(
            model_name='conhecametas',
            name='metas_mais_50',
        ),
        migrations.RemoveField(
            model_name='conhecametas',
            name='recursos_empenhados',
        ),
        migrations.AddField(
            model_name='conhecametas',
            name='ordem',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ordem de Aparição'),
        ),
        migrations.AddField(
            model_name='conhecametas',
            name='valor',
            field=models.CharField(null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='conhecametas',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Título'),
        ),
    ]
