# Generated by Django 5.2.4 on 2026-03-27 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0044_remove_conhecametas_execucao_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conhecametas',
            name='ordem',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ordem de Aparição'),
        ),
    ]
