# Generated by Django 5.2.4 on 2026-04-10 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0045_alter_conhecametas_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestesDebora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('valor_aleatorio', models.CharField(null=True, verbose_name='Valor')),
                ('ordem_aparicao', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ordem de Aparição')),
                ('regra', models.BooleanField(default=False, verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Teste',
                'verbose_name_plural': 'Testes',
            },
        ),
    ]
