# Generated by Django 5.2.4 on 2026-04-14 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura_pdm', '0046_testesdebora'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbinhaDebora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_abinha', models.CharField(max_length=500, null=True, verbose_name='Cor')),
                ('fruta', models.CharField(default='Morango', max_length=500, verbose_name='Fruta')),
                ('quantidade_abinha', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('teste_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abinha_da_debora', to='estrutura_pdm.testesdebora', verbose_name='Teste relacionado')),
            ],
        ),
    ]
