# Generated by Django 5.2.4 on 2025-08-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='cd_geosampa',
            field=models.IntegerField(default=1, verbose_name='Código Geosampa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subprefeitura',
            name='cd_geosampa',
            field=models.IntegerField(default=1, verbose_name='Código Geosampa'),
            preserve_default=False,
        ),
    ]
