# Generated by Django 5.2.4 on 2025-08-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0002_distrito_cd_geosampa_subprefeitura_cd_geosampa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='cd_geosampa',
            field=models.IntegerField(unique=True, verbose_name='Código Geosampa'),
        ),
        migrations.AlterField(
            model_name='subprefeitura',
            name='cd_geosampa',
            field=models.IntegerField(unique=True, verbose_name='Código Geosampa'),
        ),
    ]
