# Generated by Django 5.2.4 on 2025-08-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0003_alter_distrito_cd_geosampa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Prefeito')),
                ('partido', models.CharField(max_length=100, verbose_name='Partido')),
                ('mandato_inicio', models.DateField(verbose_name='Início do Mandato')),
                ('mandato_fim', models.DateField(blank=True, null=True, verbose_name='Fim do Mandato')),
            ],
            options={
                'verbose_name': 'Prefeito',
                'verbose_name_plural': 'Prefeitos',
            },
        ),
    ]
