# Generated by Django 5.2.4 on 2025-08-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0004_prefeito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgao',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do Órgão'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='sigla',
            field=models.CharField(max_length=10, unique=True, verbose_name='Sigla do Órgão'),
        ),
    ]
