# Generated by Django 5.2.4 on 2025-08-13 15:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0005_alter_orgao_nome_alter_orgao_sigla'),
        ('static_files', '0002_alter_imagem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número da ODS (ex: 1, 2, 3, etc.)', unique=True, verbose_name='Número da ODS')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do ODS')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do ODS')),
                ('cor_principal', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal no formato #RRGGBB (ex: #1A2B3C).', regex='^#([A-Fa-f0-9]{6})$')], verbose_name='Cor Principal do ODS')),
                ('logo_branco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ods_branco', to='static_files.imagem', verbose_name='Logo do ODS (Branco)')),
                ('logo_colorido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ods', to='static_files.imagem', verbose_name='Logo do ODS')),
            ],
            options={
                'verbose_name': 'ODS',
                'verbose_name_plural': 'ODS',
                'ordering': ['numero'],
            },
        ),
    ]
