# Generated by Django 5.2.4 on 2025-08-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0006_ods'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoSetorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000, verbose_name='Nome do Plano Setorial')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Plano Setorial')),
            ],
        ),
    ]
