# Generated by Django 5.2.4 on 2025-08-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0007_planosetorial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planosetorial',
            options={'ordering': ['nome'], 'verbose_name': 'Plano Setorial', 'verbose_name_plural': 'Planos Setoriais'},
        ),
    ]
