# Generated by Django 5.2.4 on 2025-08-26 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0008_alter_planosetorial_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Zona')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla da Zona')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['sigla'],
            },
        ),
        migrations.AddField(
            model_name='subprefeitura',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprefeituras', to='cadastros_basicos.zona'),
        ),
    ]
