# Generated by Django 5.2.4 on 2025-08-25 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0009_zona_subprefeitura_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprefeitura',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprefeituras', to='cadastros_basicos.zona'),
        ),
    ]
